### ISSUE TITLE
'child confirmation'?

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/parent-signals-dot#23]
As requested by Paul Wouters. The most complete message about it is https://mailarchive.ietf.org/arch/msg/dns-privacy/v8qUTMNVW_9W25GUXVStr2_Jk-A

I don't see a big problem with doing it, but I am still not fully comprehending the problem.

**Comment by RobinGeuze** [comment]
Child confirmation does not make much sense to require. Paul states that it is need to defend against malicious parents adding an extra DS record, however if you can add an extra DS record why not also just add a normal DS record for a DNSKEY and fake everything in the child, ergo it does not offer any additional protection in anyway.

I suspect the logic comes from the fact that yopu should validate the NS records in the child, however that is due to the fact that NS records in the parent are unsigned, DS records do not have that problem.

**Comment by RobinGeuze** [comment]
Shall we close this? I feel we should not put this in the RFC, I see no valid reason or added benefit.

**Comment by Habbie** [comment]
Yes. We can always reopen.
