### ISSUE TITLE
Different Domain same nameserver(s)

### ISSUE THREAD

**Issue by RobinGeuze** [PowerDNS/parent-signals-dot#4]
If a nameserver hostname is encountered on a domain with a DoT DS record and it works properly and after this it is encountered on another domain without a DoT DS record a resolver MAY assume DoT will work and use that.

**Comment by RobinGeuze** [comment]
Note: since the DS hash includes the domain name the pub key returned should be verified with the old domain or not at all?

**Comment by Habbie** [comment]
> Note: since the DS hash includes the domain name the pub key returned should be verified with the old domain or not at all?

If we know, from a previous lookup in a domain that had a DoT-signaling DS, that a name server does DoT, then we have also had an opportunity to learn and verify the cert!

**Comment by Habbie** [comment]
We should be careful remembering name/key associations, though - what if example.com makes a DS claim about ns.example.org, while MITMing it, and we remember the claim when we later do a lookup in example.org? This is similar to the (off-github) discussion we had about using names and cert chains.

**Comment by RobinGeuze** [comment]
This however does not degrade the security compared the the existing situation. As long as the domain has DNSSEC enabled it should be secure from MITM attacks, if it does not its vulnerable.

**Comment by Habbie** [comment]
Yes, but -if- we are going to, at some point, have the discussion 'is DoT enough for AD=1?', these things suddenly matter a lot!

**Comment by Habbie** [comment]
Tagged this 'undecided' because I haven't managed to wrap my head around any negative implications yet.

**Comment by chantra** [comment]
I guess on one hand, the owner of the domain which does not signal DoT may simply not want to have DoT used, say because of reliability or what not. This may prevent that owner form disabling DoT on their zones.

I also wonder which attack this could surface. Don't we get to something similar to [glue cache poisoning](https://cr.yp.to/djbdns/notes.html#poison)?

Say good.example.net has ns1.example.com and ns2.example.com and does not signal DoT-DS.
comes evil.example.org with the same name servers and signal-DoT-DS with it's own hash, if glue is used and you can steer traffic to name servers controlled by evil.example.org, you could make DoT work for evil.example.org and make it fail for good.example.net?

**Comment by Habbie** [comment]
Thank you for reminding me of glue, that's a lot easier than an MITM attack!

Let's keep this out of the draft for now.

**Comment by RobinGeuze** [comment]
I think we can close this as well?
