### ISSUE TITLE
All nameservers for a domain SHOULD support DoT

### ISSUE THREAD

**Issue by RobinGeuze** [PowerDNS/parent-signals-dot#5]
If you set the DS record in the parent all the nameservers in the NS-set should support DoT on all their associated IP addresses. IOf a nameserver does not support DoT it is recommended that you make sure it will return a RST response on port 853 to prevent resolving slow downs.

**Comment by Habbie** [comment]
I believe this is covered in https://github.com/PowerDNS/parent-signals-dot/blob/master/draft-vandijk-dprive-ds-dot-signal-and-pin/draft-vandijk-dprive-ds-dot-signal-and-pin.md#authoritative-server-changes now, do you agree?

**Comment by RobinGeuze** [comment]
Yes, I agree

**Comment by chantra** [comment]
A side effect of the RST is that now, someone on-path can downgrade to plain text by RSTing any requests to TCP/853.
In order to prevent such downgrading, I suppose a resolver, that wants to operate in strict mode, can decide to:
1. favor nameservers that can do DoT, e.g only use those name servers and not the ones that can't be reached over DoT.
1. SERVFAIL if none of the nameservers are available over DoT and a DS record signals that DoT is supported.

**Comment by RobinGeuze** [comment]
That is actually a good point, I'll draft some text for this.

**Comment by RobinGeuze** [comment]
Oh I just noticed we already have this text in the draft:
```
If a resolver with support for TBD encounters a DS record with the DNSKEY algorithm type TBD it MUST connect to the authoritative servers for this domain via DoT.
It MUST use the hashes attached to the DS records with DNSKEY algorithm type TBD to check whether the public key supplied by the authoritative nameserver is valid.
If the DoT connection is unsuccessful or the public key supplied the server does not match one of the DS digests, the resolver MUST NOT fall back to unencrypted Do53.
```
I think that covers that case pretty clearly.
